export const SET_FILMS = 'SET_FILMS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SERVER_PAGE = 'SET_SERVER_PAGE';
export const SET_FILM_DETAIL = 'SET_FILM_DETAIL';
export const SET_ACTORS = 'SET_ACTORS';
export const SET_ACTOR_DETAIL = 'SET_ACTOR_DETAIL';
export const SET_SEARCHED_FILMS = 'SET_SEARCHED_FILMS';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
